version: '3.5'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
